// @vitest-environment jsdom
/**
 * Render regression tests for the per-block mula presentation (IDEA.md).
 *
 * A main passage whose `kind` classifies as "prose" (Para/Gadya) must render
 * undecorated: no `border-l-2` bar, no `max-w-2xl` centering, `flow-commentary`
 * type, and no appended `॥ N ॥`. A "verse" kind keeps the current verse
 * decoration. The decision is `presentationFor(passage.kind)` — a total
 * function — so the assertions pin both the mapping and its application in the
 * FlowReader mula block.
 */

import { describe, it, expect, afterEach, beforeAll } from "vitest";
import { act } from "react-dom/test-utils";
import { createRoot, Root } from "react-dom/client";
import React from "react";
import { Grantha, GranthaMetadata } from "@/lib/data";
import FlowReader from "./FlowReader";

const emptyGranthasMeta: GranthaMetadata[] = [];

const makeGrantha = (kind: "Para" | "Shloka"): Grantha => ({
  grantha_id: "test-grantha",
  edition_id: "test-grantha",
  canonical_title: "टेस्ट",
  aliases: [],
  text_type: kind === "Para" ? "prakarana" : "purana",
  language: "sanskrit",
  metadata: {
    source_url: null,
    source_commit: null,
    source_file: "test.md",
    processing_pipeline: {},
    quality_notes: "",
    last_updated: "",
  },
  structure_levels: [
    { key: kind, scriptNames: { devanagari: kind === "Para" ? "पाठः" : "श्लोकः" } },
  ],
  prefatory_material: [],
  passages: [
    {
      ref: "1",
      passage_type: "main",
      kind,
      content: {
        sanskrit: { devanagari: "अयं पाठः" },
        english_translation: "",
      },
    },
  ],
  concluding_material: [],
  commentaries: [],
  id: "test-grantha",
  path: "test-grantha",
  title: "टेस्ट",
  title_deva: "टेस्ट",
  title_iast: "test",
  categories: [],
});

const propsFor = (grantha: Grantha) => ({
  grantha,
  editions: [grantha],
  editionsMeta: [],
  editionIds: [grantha.edition_id ?? grantha.grantha_id],
  onEditionIdsChange: () => {},
  granthas: emptyGranthasMeta,
  selectedRef: "1",
  onGranthaChange: () => {},
  onVerseSelect: () => {},
  onScrollVerseChange: () => {},
  activeSubcommentaryIds: undefined,
  onSubcommentaryToggle: () => {},
  loadPart: async () => {},
  isLoadingPart: false,
  onExitFlow: () => {},
  script: "deva" as const,
  onScriptChange: () => {},
  updateHash: () => {},
  availableGranthaIds: ["test-grantha"],
  granthaById: {},
  granthaIdToDevanagariTitle: {},
});

beforeAll(() => {
  for (const [name, impl] of Object.entries({
    ResizeObserver: class {
      observe() {}
      unobserve() {}
      disconnect() {}
    },
    IntersectionObserver: class {
      observe() {}
      unobserve() {}
      disconnect() {}
    },
  })) {
    (globalThis as Record<string, unknown>)[name] =
      (globalThis as Record<string, unknown>)[name] ?? impl;
  }
});

const renderInto = (node: React.ReactNode): { root: Root; el: HTMLDivElement } => {
  const el = document.createElement("div");
  document.body.appendChild(el);
  const root = createRoot(el);
  root.render(node);
  return { root, el };
};

const cleanUp = (root: Root, el: HTMLDivElement) => {
  act(() => root.unmount());
  el.remove();
};

const mulaTextEl = (el: HTMLElement): HTMLElement | null =>
  el.querySelector<HTMLElement>('[data-verse-ref="1"] .verse-text');

describe("FlowReader per-block mula presentation", () => {
  afterEach(() => {
    document.body.innerHTML = "";
  });

  it("renders a Para (prose) mula undecorated but numbered", async () => {
    const grantha = makeGrantha("Para");
    const { root, el } = renderInto(<FlowReader {...propsFor(grantha)} />);
    await act(async () => {});
    const text = mulaTextEl(el);
    expect(text).not.toBeNull();
    expect(text!.className).toContain("flow-commentary");
    expect(text!.className).not.toContain("flow-verse");
    // no verse chrome anywhere in the passage block
    const block = el.querySelector<HTMLElement>('[data-verse-ref="1"]');
    expect(block!.querySelector(".border-l-2")).toBeNull();
    // the passage number is autogenerated in double dandas like verse texts
    expect(text!.textContent).toContain("॥ १॥");
    cleanUp(root, el);
  });

  it("renders a Shloka (verse) mula decorated", async () => {
    const grantha = makeGrantha("Shloka");
    const { root, el } = renderInto(<FlowReader {...propsFor(grantha)} />);
    await act(async () => {});
    const text = mulaTextEl(el);
    expect(text).not.toBeNull();
    expect(text!.className).toContain("flow-verse");
    expect(text!.className).not.toContain("flow-commentary");
    const block = el.querySelector<HTMLElement>('[data-verse-ref="1"]');
    expect(block!.querySelector(".border-l-2")).not.toBeNull();
    cleanUp(root, el);
  });
});
